#!/usr/bin/env python3
"""Build complete questions.json with 100 multilingual football quiz questions."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from generate_questions import WORLD_CUP
from quiz_helpers import LOCALES, make_id, q, L, O
from categories_part2 import FOOTBALL_RULES
from categories_part3 import LEGENDS, CURRENT_FOOTBALL

CHAMPIONS_LEAGUE = [
    (L("Which club has won the most UEFA Champions League titles?", "Koji klub ima najviše naslova UEFA Lige prvaka?", "Welcher Verein hat die meisten UEFA-Champions-League-Titel gewonnen?", "Koji klub ima najviše naslova UEFA Lige prvaka?", "¿Qué club ha ganado más títulos de la UEFA Champions League?", "Qual clube venceu mais títulos da UEFA Champions League?", "Који клуб има највише титула УЕФА Лиге шампиона?", "Quel club a remporté le plus de titres de Ligue des champions de l'UEFA ?", "Quale club ha vinto più titoli di UEFA Champions League?", "Welke club heeft de meeste UEFA Champions League-titels gewonnen?", "Hangi kulüp en fazla UEFA Şampiyonlar Ligi şampiyonluğuna sahiptir?", "أي نادٍ فاز بأكبر عدد من ألقاب دوري أبطال أوروبا؟"),
     O(["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern München", "Liverpool"], ["Real Madrid", "AC Mailand", "Bayern München", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern München", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern Múnich", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern de Munique", "Liverpool"], ["Реал Мадрид", "АЦ Милан", "Бајерн Минхен", "Ливерпул"], ["Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"], ["Real Madrid", "Milan", "Bayern Monaco", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern München", "Liverpool"], ["Real Madrid", "AC Milan", "Bayern Münih", "Liverpool"], ["ريال مدريد", "ميلان", "بايرن ميونخ", "ليفربول"]), 0),
    (L("Who scored the winning goal in the 1999 Champions League final for Manchester United?", "Tko je postigao pobjednički gol u finalu Lige prvaka 1999. za Manchester United?", "Wer erzielte das Siegtor im Champions-League-Finale 1999 für Manchester United?", "Ko je postigao pobjednički gol u finalu Lige prvaka 1999. za Manchester United?", "¿Quién marcó el gol de la victoria en la final de 1999 de la Champions League para el Manchester United?", "Quem marcou o gol da vitória na final de 1999 da Champions League pelo Manchester United?", "Ко је постигао победоносни гол у финалу Лиге шампиона 1999. за Манчестер Јунајтед?", "Qui a marqué le but victorieux en finale de la Ligue des champions 1999 pour Manchester United ?", "Chi segnò il gol della vittoria nella finale di Champions League 1999 per il Manchester United?", "Wie scoorde het winnende doelpunt in de Champions League-finale van 1999 voor Manchester United?", "1999 Şampiyonlar Ligi finalinde Manchester United adına galibiyet golünü kim attı?", "من سجل هدف الفوز في نهائي دوري الأبطال 1999 مع مانشستر يونايتد؟"),
     O(["Teddy Sheringham & Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham i Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham & Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham i Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham y Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham e Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Теди Шерингем и Оле Гунар Солскјер", "Дејвид Бекам", "Рајан Гигс", "Пол Сколс"], ["Teddy Sheringham et Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham e Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham & Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["Teddy Sheringham ve Ole Gunnar Solskjær", "David Beckham", "Ryan Giggs", "Paul Scholes"], ["تيدي شيرينغهام وأولي غونار سولسشاير", "ديفيد بيكهام", "رايان غيغز", "بول سكولز"]), 0),
    (L("Which player has scored the most goals in Champions League history?", "Koji je igrač postigao najviše golova u povijesti Lige prvaka?", "Welcher Spieler hat die meisten Tore in der Champions-League-Geschichte erzielt?", "Koji je igrač postigao najviše golova u historiji Lige prvaka?", "¿Qué jugador ha marcado más goles en la historia de la Champions League?", "Qual jogador marcou mais gols na história da Champions League?", "Који играч је постигао највише голова у историји Лиге шампиона?", "Quel joueur a marqué le plus de buts dans l'histoire de la Ligue des champions ?", "Quale giocatore ha segnato più gol nella storia della Champions League?", "Welke speler heeft de meeste doelpunten gescoord in de Champions League-geschiedenis?", "Şampiyonlar Ligi tarihinin en golcü oyuncusu kimdir?", "من هو الهداف التاريخي لدوري أبطال أوروبا؟"),
     O(["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Кристијано Роналдо", "Лионел Меси", "Роберт Левандовски", "Карим Бензема"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"], ["كريستيانو رونالدو", "ليونيل ميسي", "روبرت ليفاندوفسكي", "كريم بنزيما"]), 0),
    (L("Which club won the 2024 UEFA Champions League?", "Koji je klub osvojio UEFA Ligu prvaka 2024.?", "Welcher Verein gewann die UEFA Champions League 2024?", "Koji je klub osvojio UEFA Ligu prvaka 2024.?", "¿Qué club ganó la UEFA Champions League 2024?", "Qual clube venceu a UEFA Champions League de 2024?", "Који је клуб освојио УЕФА Лигу шампиона 2024.?", "Quel club a remporté la Ligue des champions de l'UEFA 2024 ?", "Quale club ha vinto la UEFA Champions League 2024?", "Welke club won de UEFA Champions League 2024?", "2024 UEFA Şampiyonlar Ligi'ni hangi kulüp kazandı?", "أي نادٍ فاز بدوري أبطال أوروبا 2024؟"),
     O(["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Munich"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern München"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern München"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern München"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Múnich"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern de Munique"], ["Реал Мадрид", "Борусија Дортмунд", "Манчестер Сити", "Бајерн Минхен"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Munich"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Monaco"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern München"], ["Real Madrid", "Borussia Dortmund", "Manchester City", "Bayern Münih"], ["ريال مدريد", "بوروسيا دورتموند", "مانشستر سيتي", "بايرن ميونخ"]), 0),
    (L("What was the Champions League called before 1992?", "Kako se Liga prvaka zvala prije 1992.?", "Wie hieß die Champions League vor 1992?", "Kako se Liga prvaka zvala prije 1992.?", "¿Cómo se llamaba la Champions League antes de 1992?", "Como se chamava a Champions League antes de 1992?", "Како се Лига шампиона звала пре 1992.?", "Comment s'appelait la Ligue des champions avant 1992 ?", "Come si chiamava la Champions League prima del 1992?", "Hoe heette de Champions League vóór 1992?", "1992'den önce Şampiyonlar Ligi'nin adı neydi?", "ما اسم دوري الأبطال قبل عام 1992؟"),
     O(["European Cup", "UEFA Cup", "Cup Winners' Cup", "Intertoto Cup"], ["Kup europskih prvaka", "UEFA kup", "Kup pobjednika kupova", "Intertoto kup"], ["Europapokal der Landesmeister", "UEFA-Pokal", "Pokal der Pokalsieger", "Intertoto-Pokal"], ["Kup europskih prvaka", "UEFA kup", "Kup pobjednika kupova", "Intertoto kup"], ["Copa de Europa", "Copa UEFA", "Recopa de Europa", "Copa Intertoto"], ["Taça dos Campeões Europeus", "Taça UEFA", "Taça das Copas", "Taça Intertoto"], ["Куп европских шампиона", "УЕФА куп", "Куп победника купова", "Интертото куп"], ["Coupe d'Europe", "Coupe UEFA", "Coupe des Coupes", "Coupe Intertoto"], ["Coppa dei Campioni", "Coppa UEFA", "Coppa delle Coppe", "Coppa Intertoto"], ["Europacup I", "UEFA Cup", "Europese Beker", "Intertoto Cup"], ["Şampiyonlar Kupası", "UEFA Kupası", "Kupa Galipleri Kupası", "Intertoto Kupası"], ["كأس الأندية الأوروبية", "كأس الاتحاد الأوروبي", "كأس الكؤوس", "كأس الإنترتوتو"]), 0),
    (L("Which stadium hosted the 2011 Champions League final?", "Koji je stadion bio domaćin finala Lige prvaka 2011.?", "Welches Stadion war Austragungsort des Champions-League-Finals 2011?", "Koji stadion je bio domaćin finala Lige prvaka 2011.?", "¿Qué estadio albergó la final de la Champions League 2011?", "Qual estádio sediou a final da Champions League de 2011?", "Који стадион је био домаћин финала Лиге шампиона 2011.?", "Quel stade a accueilli la finale de la Ligue des champions 2011 ?", "Quale stadio ha ospitato la finale di Champions League 2011?", "Welk stadion organiseerde de Champions League-finale van 2011?", "2011 Şampiyonlar Ligi finaline hangi stadyum ev sahipliği yaptı?", "أي ملعب استضاف نهائي دوري الأبطال 2011؟"),
     O(["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Estadio de Wembley", "Camp Nou", "Allianz Arena", "San Siro"], ["Estádio de Wembley", "Camp Nou", "Allianz Arena", "San Siro"], ["Вембли", "Камп Ноу", "Алијанц Арена", "Сан Сиро"], ["Stade de Wembley", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadium", "Camp Nou", "Allianz Arena", "San Siro"], ["Wembley Stadyumu", "Camp Nou", "Allianz Arena", "San Siro"], ["ملعب ويمبلي", "كامب نو", "أليانز أرينا", "سان سيرو"]), 0),
    (L("Which club completed 'La Decimocuarta' by winning the 2024 Champions League?", "Koji je klub osvojio 'La Decimocuarta' pobjedom u Ligi prvaka 2024.?", "Welcher Verein vollendete 'La Decimocuarta' mit dem Sieg in der Champions League 2024?", "Koji klub je osvojio 'La Decimocuarta' pobjedom u Ligi prvaka 2024.?", "¿Qué club completó 'La Decimocuarta' al ganar la Champions League 2024?", "Qual clube completou a 'La Decimocuarta' ao vencer a Champions League de 2024?", "Који је клуб освојио 'La Decimocuarta' победом у Лиги шампиона 2024.?", "Quel club a accompli 'La Decimocuarta' en remportant la Ligue des champions 2024 ?", "Quale club ha completato la 'La Decimocuarta' vincendo la Champions League 2024?", "Welke club voltooide 'La Decimocuarta' door de Champions League 2024 te winnen?", "2024 Şampiyonlar Ligi'ni kazanarak 'La Decimocuarta'yı hangi kulüp tamamladı?", "أي نادٍ حقق 'لا ديسيموكواترا' بفوزه بدوري الأبطال 2024؟"),
     O(["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Реал Мадрид", "Барселона", "Атлетико Мадрид", "Севиља"], ["Real Madrid", "Barcelone", "Atlético Madrid", "Séville"], ["Real Madrid", "Barcellona", "Atlético Madrid", "Siviglia"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["Real Madrid", "Barcelona", "Atlético Madrid", "Sevilla"], ["ريال مدريد", "برشلونة", "أتلتيكو مدريد", "إشبيلية"]), 0),
    (L("Who managed Liverpool to their 2019 Champions League triumph?", "Tko je vodio Liverpool do trijumfa u Ligi prvaka 2019.?", "Wer trainierte Liverpool zum Champions-League-Triumph 2019?", "Ko je vodio Liverpool do trijumfa u Ligi prvaka 2019.?", "¿Quién dirigió al Liverpool en su triunfo en la Champions League 2019?", "Quem treinou o Liverpool no triunfo na Champions League de 2019?", "Ко је водио Ливерпул до тријумфа у Лиги шампиона 2019.?", "Qui a entraîné Liverpool lors de son triomphe en Ligue des champions 2019 ?", "Chi ha allenato il Liverpool al trionfo in Champions League 2019?", "Wie traineerde Liverpool naar de Champions League-triomf in 2019?", "2019 Şampiyonlar Ligi zaferinde Liverpool'u hangi teknik direktör yönetti?", "من أدرب ليفربول في فوزه بدوري الأبطال 2019؟"),
     O(["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Јирген Клоп", "Брендан Роджерс", "Рафаел Бенитез", "Кени Далглиш"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["Jürgen Klopp", "Brendan Rodgers", "Rafael Benítez", "Kenny Dalglish"], ["يورغن كلوب", "برندان رودجرز", "رافائيل بينيتيز", "كيني دالغليش"]), 0),
    (L("Which club won the first UEFA Champions League season in 1992-93?", "Koji je klub osvojio prvu sezonu UEFA Lige prvaka 1992./93.?", "Welcher Verein gewann die erste UEFA-Champions-League-Saison 1992/93?", "Koji klub je osvojio prvu sezonu UEFA Lige prvaka 1992./93.?", "¿Qué club ganó la primera temporada de la UEFA Champions League 1992-93?", "Qual clube venceu a primeira temporada da UEFA Champions League em 1992-93?", "Који је клуб освојио прву сезону УЕФА Лиге шампиона 1992/93.?", "Quel club a remporté la première saison de la Ligue des champions de l'UEFA en 1992-93 ?", "Quale club ha vinto la prima stagione di UEFA Champions League nel 1992-93?", "Welke club won het eerste UEFA Champions League-seizoen in 1992-93?", "1992-93 sezonunun ilk UEFA Şampiyonlar Ligi'ni hangi kulüp kazandı?", "أي نادٍ فاز بأول موسم لدوري أبطال أوروبا 1992-93؟"),
     O(["Olympique Marseille", "AC Milan", "Barcelona", "Ajax"], ["Olympique Marseille", "AC Milan", "Barcelona", "Ajax"], ["Olympique Marseille", "AC Mailand", "Barcelona", "Ajax"], ["Olympique Marseille", "AC Milan", "Barcelona", "Ajax"], ["Olympique de Marsella", "AC Milan", "Barcelona", "Ajax"], ["Olympique de Marselha", "AC Milan", "Barcelona", "Ajax"], ["Олимпик Марсељ", "АЦ Милан", "Барселона", "Ајакс"], ["Olympique de Marseille", "AC Milan", "Barcelone", "Ajax"], ["Olympique Marsiglia", "Milan", "Barcellona", "Ajax"], ["Olympique Marseille", "AC Milan", "Barcelona", "Ajax"], ["Olympique Marseille", "AC Milan", "Barcelona", "Ajax"], ["أولمبيك مارسيليا", "ميلان", "برشلونة", "أياكس"]), 0),
    (L("Which player scored a hat-trick against Liverpool in the 2018 Champions League final?", "Koji je igrač postigao tri gola protiv Liverpoola u finalu Lige prvaka 2018.?", "Welcher Spieler erzielte einen Hattrick gegen Liverpool im Champions-League-Finale 2018?", "Koji igrač je postigao tri gola protiv Liverpoola u finalu Lige prvaka 2018.?", "¿Qué jugador marcó un hat-trick contra el Liverpool en la final de la Champions League 2018?", "Qual jogador marcou um hat-trick contra o Liverpool na final da Champions League de 2018?", "Који играч је постигао три гола против Ливерпула у финалу Лиге шампиона 2018.?", "Quel joueur a marqué un triplé contre Liverpool en finale de la Ligue des champions 2018 ?", "Quale giocatore segnò una tripletta contro il Liverpool nella finale di Champions League 2018?", "Welke speler scoorde een hattrick tegen Liverpool in de Champions League-finale van 2018?", "2018 Şampiyonlar Ligi finalinde Liverpool'a karşı hat-trick yapan oyuncu kimdir?", "من سجل ثلاثية ضد ليفربول في نهائي دوري الأبطال 2018؟"),
     O(["Mohamed Salah did not; Gareth Bale scored twice", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah nije; Gareth Bale postigao dva gola", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah nicht; Gareth Bale erzielte zweimal", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah nije; Gareth Bale postigao dva gola", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah no; Gareth Bale marcó dos veces", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah não; Gareth Bale marcou duas vezes", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Мохамед Салах није; Гарет Бејл постигао два гола", "Мохамед Салах", "Садио Мане", "Роберто Фирмино"], ["Mohamed Salah non; Gareth Bale a marqué deux fois", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah no; Gareth Bale segnò due volte", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah niet; Gareth Bale scoorde tweemaal", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["Mohamed Salah değil; Gareth Bale iki gol attı", "Mohamed Salah", "Sadio Mané", "Roberto Firmino"], ["لم يكن محمد صلاح؛ سجل غاريث بيل مرتين", "محمد صلاح", "ساديو ماني", "روبرتو فيرمينو"]), 1),
]

# Fix question 10 - it was wrong. Let me use a proper question instead.
CHAMPIONS_LEAGUE[9] = (
    L("Who scored two goals for Real Madrid in the 2018 Champions League final?", "Tko je postigao dva gola za Real Madrid u finalu Lige prvaka 2018.?", "Wer erzielte zwei Tore für Real Madrid im Champions-League-Finale 2018?", "Ko je postigao dva gola za Real Madrid u finalu Lige prvaka 2018.?", "¿Quién marcó dos goles para el Real Madrid en la final de la Champions League 2018?", "Quem marcou dois gols pelo Real Madrid na final da Champions League de 2018?", "Ко је постигао два гола за Реал Мадрид у финалу Лиге шампиона 2018.?", "Qui a marqué deux buts pour le Real Madrid en finale de la Ligue des champions 2018 ?", "Chi segnò due gol per il Real Madrid nella finale di Champions League 2018?", "Wie scoorde twee doelpunten voor Real Madrid in de Champions League-finale van 2018?", "2018 Şampiyonlar Ligi finalinde Real Madrid adına iki gol atan oyuncu kimdir?", "من سجل هدفين لريال مدريد في نهائي دوري الأبطال 2018؟"),
    O(["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Гарет Бејл", "Кристијано Роналдо", "Карим Бензема", "Иско"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["Gareth Bale", "Cristiano Ronaldo", "Karim Benzema", "Isco"], ["غاريث بيل", "كريستيانو رونالدو", "كريم بنزيما", "إيسكو"]), 0)

CHAMPIONS_LEAGUE.extend([
    (L("Which club is nicknamed 'The Old Lady' and has won multiple Champions League titles?", "Koji klub nosi nadimak 'Stara dama' i ima više naslova Lige prvaka?", "Welcher Verein trägt den Spitznamen 'Die alte Dame' und hat mehrere Champions-League-Titel gewonnen?", "Koji klub nosi nadimak 'Stara dama' i ima više naslova Lige prvaka?", "¿Qué club tiene el apodo 'La Vieja Señora' y ha ganado varios títulos de Champions League?", "Qual clube tem o apelido 'A Velha Senhora' e venceu vários títulos da Champions League?", "Који клуб носи надимак 'Стара дама' и има више титула Лиге шампиона?", "Quel club porte le surnom 'La Vieille Dame' et a remporté plusieurs titres de Ligue des champions ?", "Quale club è soprannominato 'La Vecchia Signora' e ha vinto più titoli di Champions League?", "Welke club heeft de bijnaam 'De Oude Dame' en won meerdere Champions League-titels?", "Birden fazla Şampiyonlar Ligi şampiyonluğu olan 'Yaşlı Hanım' lakaplı kulüp hangisidir?", "أي نادٍ يلقب بـ'السيدة العجوز' وفاز بعدة ألقاب في دوري الأبطال؟"),
     O(["Juventus", "Inter Milan", "AC Milan", "AS Roma"], ["Juventus", "Inter Milano", "AC Milan", "AS Roma"], ["Juventus", "Inter Mailand", "AC Mailand", "AS Rom"], ["Juventus", "Inter Milano", "AC Milan", "AS Roma"], ["Juventus", "Inter de Milán", "AC Milan", "AS Roma"], ["Juventus", "Inter de Milão", "AC Milan", "AS Roma"], ["Јувентус", "Интер", "АЦ Милан", "АС Рома"], ["Juventus", "Inter Milan", "AC Milan", "AS Rome"], ["Juventus", "Inter", "Milan", "Roma"], ["Juventus", "Inter Milan", "AC Milan", "AS Roma"], ["Juventus", "Inter Milan", "AC Milan", "AS Roma"], ["يوفنتوس", "إنتر ميلان", "ميلان", "روما"]), 0),
    (L("Which club won the 2023 UEFA Champions League?", "Koji je klub osvojio UEFA Ligu prvaka 2023.?", "Welcher Verein gewann die UEFA Champions League 2023?", "Koji klub je osvojio UEFA Ligu prvaka 2023.?", "¿Qué club ganó la UEFA Champions League 2023?", "Qual clube venceu a UEFA Champions League de 2023?", "Који је клуб освојио УЕФА Лигу шампиона 2023.?", "Quel club a remporté la Ligue des champions de l'UEFA 2023 ?", "Quale club ha vinto la UEFA Champions League 2023?", "Welke club won de UEFA Champions League 2023?", "2023 UEFA Şampiyonlar Ligi'ni hangi kulüp kazandı?", "أي نادٍ فاز بدوري أبطال أوروبا 2023؟"),
     O(["Manchester City", "Inter Milan", "Real Madrid", "Bayern Munich"], ["Manchester City", "Inter Milano", "Real Madrid", "Bayern München"], ["Manchester City", "Inter Mailand", "Real Madrid", "Bayern München"], ["Manchester City", "Inter Milano", "Real Madrid", "Bayern München"], ["Manchester City", "Inter de Milán", "Real Madrid", "Bayern Múnich"], ["Manchester City", "Inter de Milão", "Real Madrid", "Bayern de Munique"], ["Манчестер Сити", "Интер", "Реал Мадрид", "Бајерн Минхен"], ["Manchester City", "Inter Milan", "Real Madrid", "Bayern Munich"], ["Manchester City", "Inter", "Real Madrid", "Bayern Monaco"], ["Manchester City", "Inter Milan", "Real Madrid", "Bayern München"], ["Manchester City", "Inter Milan", "Real Madrid", "Bayern Münih"], ["مانشستر سيتي", "إنتر ميلان", "ريال مدريد", "بايرن ميونخ"]), 0),
    (L("Which player won the 2024 Champions League final Man of the Match award?", "Koji je igrač osvojio nagradu za najboljeg igrača finala Lige prvaka 2024.?", "Welcher Spieler gewann die Auszeichnung als Spieler des Spiels im Champions-League-Finale 2024?", "Koji igrač je osvojio nagradu za najboljeg igrača finala Lige prvaka 2024.?", "¿Qué jugador ganó el premio al mejor jugador de la final de la Champions League 2024?", "Qual jogador venceu o prêmio de melhor em campo na final da Champions League de 2024?", "Који играч је освојио награду за најбољег играча финала Лиге шампиона 2024.?", "Quel joueur a remporté le prix de l'homme du match en finale de la Ligue des champions 2024 ?", "Quale giocatore ha vinto il premio uomo partita nella finale di Champions League 2024?", "Welke speler won de man of the match in de Champions League-finale van 2024?", "2024 Şampiyonlar Ligi finalinde maçın oyuncusu ödülünü kim kazandı?", "من فاز بجائزة أفضل لاعب في نهائي دوري الأبطال 2024؟"),
     O(["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Родриго", "Винисијус Жуниор", "Џуд Белингем", "Дани Карвахал"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["Rodrygo", "Vinícius Júnior", "Jude Bellingham", "Dani Carvajal"], ["رودريغو", "فينيسيوس جونيور", "جود بيلينغهام", "داني كارفاخال"]), 3),
    (L("Which Italian club has won the most Champions League/European Cup titles?", "Koji talijanski klub ima najviše naslova Lige prvaka/Kupa europskih prvaka?", "Welcher italienische Verein hat die meisten Champions-League-/Europapokal-Titel?", "Koji italijanski klub ima najviše naslova Lige prvaka/Kupa europskih prvaka?", "¿Qué club italiano ha ganado más títulos de Champions League/Copa de Europa?", "Qual clube italiano venceu mais títulos da Champions League/Taça dos Campeões?", "Који италијански клуб има највише титула Лиге шампиона/Купа шампиона?", "Quel club italien a remporté le plus de titres de Ligue des champions/Coupe d'Europe ?", "Quale club italiano ha vinto più titoli di Champions League/Coppa dei Campioni?", "Welke Italiaanse club heeft de meeste Champions League/Europacup-titels?", "En fazla Şampiyonlar Ligi/Avrupa Kupası şampiyonluğuna sahip İtalyan kulüp hangisidir?", "أي نادٍ إيطالي فاز بأكبر عدد من ألقاب دوري الأبطال/كأس الأندية الأوروبية؟"),
     O(["AC Milan", "Inter Milan", "Juventus", "AS Roma"], ["AC Milan", "Inter Milano", "Juventus", "AS Roma"], ["AC Mailand", "Inter Mailand", "Juventus", "AS Rom"], ["AC Milan", "Inter Milano", "Juventus", "AS Roma"], ["AC Milan", "Inter de Milán", "Juventus", "AS Roma"], ["AC Milan", "Inter de Milão", "Juventus", "AS Roma"], ["АЦ Милан", "Интер", "Јувентус", "АС Рома"], ["AC Milan", "Inter Milan", "Juventus", "AS Rome"], ["Milan", "Inter", "Juventus", "Roma"], ["AC Milan", "Inter Milan", "Juventus", "AS Roma"], ["AC Milan", "Inter Milan", "Juventus", "AS Roma"], ["ميلان", "إنتر ميلان", "يوفنتوس", "روما"]), 0),
    (L("Which club did Bayern Munich beat 8-2 in the 2020 Champions League quarter-final?", "Koga je Bayern München pobijedio sa 8-2 u četvrtfinalu Lige prvaka 2020.?", "Welchen Verein besiegte Bayern München mit 8:2 im Champions-League-Viertelfinale 2020?", "Koga je Bayern München pobijedio sa 8-2 u četvrtfinalu Lige prvaka 2020.?", "¿A qué club venció el Bayern Múnich por 8-2 en los cuartos de final de la Champions League 2020?", "Qual clube o Bayern de Munique venceu por 8 a 2 nas quartas de final da Champions League de 2020?", "Кога је Бајерн Минхен победио са 8:2 у четвртфиналу Лиге шампиона 2020.?", "Quel club le Bayern Munich a-t-il battu 8-2 en quarts de finale de la Ligue des champions 2020 ?", "Quale club il Bayern Monaco sconfisse 8-2 nei quarti di finale di Champions League 2020?", "Welke club versloeg Bayern München met 8-2 in de Champions League-kwartfinale van 2020?", "2020 Şampiyonlar Ligi çeyrek finalinde Bayern Münih hangi kulübü 8-2 yendi?", "أي نادٍ هزمه بايرن ميونخ 8-2 في ربع نهائي دوري الأبطال 2020؟"),
     O(["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Барселона", "Челси", "Јувентус", "Лион"], ["Barcelone", "Chelsea", "Juventus", "Lyon"], ["Barcellona", "Chelsea", "Juventus", "Lione"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["Barcelona", "Chelsea", "Juventus", "Lyon"], ["برشلونة", "تشيلسي", "يوفنتوس", "ليون"]), 0),
    (L("Which club won the 2012 Champions League final at their own stadium?", "Koji je klub osvojio finale Lige prvaka 2012. na vlastitom stadionu?", "Welcher Verein gewann das Champions-League-Finale 2012 im eigenen Stadion?", "Koji klub je osvojio finale Lige prvaka 2012. na vlastitom stadionu?", "¿Qué club ganó la final de la Champions League 2012 en su propio estadio?", "Qual clube venceu a final da Champions League de 2012 no próprio estádio?", "Који је клуб освојио финале Лиге шампиона 2012. на сопственом стадиону?", "Quel club a remporté la finale de la Ligue des champions 2012 dans son propre stade ?", "Quale club ha vinto la finale di Champions League 2012 nel proprio stadio?", "Welke club won de Champions League-finale van 2012 in het eigen stadion?", "2012 Şampiyonlar Ligi finalini kendi stadyumunda hangi kulüp kazandı?", "أي نادٍ فاز بنهائي دوري الأبطال 2012 في ملعبه؟"),
     O(["Bayern Munich", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern München", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern München", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern München", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern Múnich", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern de Munique", "Chelsea", "Real Madrid", "Barcelona"], ["Бајерн Минхен", "Челси", "Реал Мадрид", "Барселона"], ["Bayern Munich", "Chelsea", "Real Madrid", "Barcelone"], ["Bayern Monaco", "Chelsea", "Real Madrid", "Barcellona"], ["Bayern München", "Chelsea", "Real Madrid", "Barcelona"], ["Bayern Münih", "Chelsea", "Real Madrid", "Barcelona"], ["بايرن ميونخ", "تشيلسي", "ريال مدريد", "برشلونة"]), 1),
    (L("Which club won three consecutive Champions League titles from 2016 to 2018?", "Koji je klub osvojio tri uzastopna naslova Lige prvaka od 2016. do 2018.?", "Welcher Verein gewann von 2016 bis 2018 drei aufeinanderfolgende Champions-League-Titel?", "Koji klub je osvojio tri uzastopna naslova Lige prvaka od 2016. do 2018.?", "¿Qué club ganó tres títulos consecutivos de Champions League de 2016 a 2018?", "Qual clube venceu três títulos consecutivos da Champions League de 2016 a 2018?", "Који је клуб освојио три узастопне титуле Лиге шампиона од 2016. до 2018.?", "Quel club a remporté trois titres consécutifs de Ligue des champions de 2016 à 2018 ?", "Quale club ha vinto tre titoli consecutivi di Champions League dal 2016 al 2018?", "Welke club won drie opeenvolgende Champions League-titels van 2016 tot 2018?", "2016'dan 2018'e kadar üst üste üç Şampiyonlar Ligi şampiyonluğu kazanan kulüp hangisidir?", "أي نادٍ فاز بثلاثة ألقاب متتالية في دوري الأبطال من 2016 إلى 2018؟"),
     O(["Real Madrid", "Barcelona", "Bayern Munich", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern München", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern München", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern München", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern Múnich", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern de Munique", "Liverpool"], ["Реал Мадрид", "Барселона", "Бајерн Минхен", "Ливерпул"], ["Real Madrid", "Barcelone", "Bayern Munich", "Liverpool"], ["Real Madrid", "Barcellona", "Bayern Monaco", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern München", "Liverpool"], ["Real Madrid", "Barcelona", "Bayern Münih", "Liverpool"], ["ريال مدريد", "برشلونة", "بايرن ميونخ", "ليفربول"]), 0),
    (L("Which Dutch club won the Champions League in 1995?", "Koji je nizozemski klub osvojio Ligu prvaka 1995.?", "Welcher niederländische Verein gewann die Champions League 1995?", "Koji holandski klub je osvojio Ligu prvaka 1995.?", "¿Qué club neerlandés ganó la Champions League en 1995?", "Qual clube holandês venceu a Champions League em 1995?", "Који холандски клуб је освојио Лигу шампиона 1995.?", "Quel club néerlandais a remporté la Ligue des champions en 1995 ?", "Quale club olandese ha vinto la Champions League nel 1995?", "Welke Nederlandse club won de Champions League in 1995?", "1995'te Şampiyonlar Ligi'ni hangi Hollanda kulübü kazandı?", "أي نادٍ هولندي فاز بدوري الأبطال عام 1995؟"),
     O(["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ајакс", "ПСВ Ајндховен", "Фејеноорд", "АЗ Алкмаар"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["Ajax", "PSV Eindhoven", "Feyenoord", "AZ Alkmaar"], ["أياكس", "بي إس في أيندهوفن", "فاينورد", "إيه زد ألكمار"]), 0),
    (L("Which club did Porto beat in the 2004 Champions League final?", "Koga je Porto pobijedio u finalu Lige prvaka 2004.?", "Welchen Verein besiegte Porto im Champions-League-Finale 2004?", "Koga je Porto pobijedio u finalu Lige prvaka 2004.?", "¿A qué club venció el Porto en la final de la Champions League 2004?", "Qual clube o Porto venceu na final da Champions League de 2004?", "Кога је Порто победио у финалу Лиге шампиона 2004.?", "Quel club Porto a-t-il battu en finale de la Ligue des champions 2004 ?", "Quale club il Porto sconfisse nella finale di Champions League 2004?", "Welke club versloeg Porto in de Champions League-finale van 2004?", "2004 Şampiyonlar Ligi finalinde Porto hangi kulübü yendi?", "أي نادٍ هزمه بورتو في نهائي دوري الأبطال 2004؟"),
     O(["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Mailand", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["AS Mónaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["АС Монако", "Челси", "АЦ Милан", "Депортиво Ла Коруња"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["Monaco", "Chelsea", "Milan", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["AS Monaco", "Chelsea", "AC Milan", "Deportivo La Coruña"], ["موناكو", "تشيلسي", "ميلان", "ديبورتيفو لاكورونيا"]), 0),
    (L("Which English club has won the most Champions League titles?", "Koji engleski klub ima najviše naslova Lige prvaka?", "Welcher englische Verein hat die meisten Champions-League-Titel?", "Koji engleski klub ima najviše naslova Lige prvaka?", "¿Qué club inglés ha ganado más títulos de Champions League?", "Qual clube inglês venceu mais títulos da Champions League?", "Који енглески клуб има највише титула Лиге шампиона?", "Quel club anglais a remporté le plus de titres de Ligue des champions ?", "Quale club inglese ha vinto più titoli di Champions League?", "Welke Engelse club heeft de meeste Champions League-titels?", "En fazla Şampiyonlar Ligi şampiyonluğuna sahip İngiliz kulüp hangisidir?", "أي نادٍ إنجليزي فاز بأكبر عدد من ألقاب دوري الأبطال؟"),
     O(["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Ливерпул", "Манчестер Јунајтед", "Челси", "Нотингем Форест"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["Liverpool", "Manchester United", "Chelsea", "Nottingham Forest"], ["ليفربول", "مانشستر يونايتد", "تشيلسي", "نوتينغهام فورست"]), 0),
])

assert len(CHAMPIONS_LEAGUE) == 20

def build_questions():
    all_data = [
        ("world_cup", WORLD_CUP),
        ("champions_league", CHAMPIONS_LEAGUE),
        ("football_rules", FOOTBALL_RULES),
        ("legends", LEGENDS),
        ("current_football", CURRENT_FOOTBALL),
    ]
    result = []
    idx = 1
    for category, items in all_data:
        assert len(items) == 20, f"{category} has {len(items)} items, expected 20"
        for text, opts, correct in items:
            obj = q(text, opts, correct, category)
            obj["id"] = make_id(idx)
            for loc in LOCALES:
                assert loc in obj["question_text"], f"Missing question_text.{loc} in {idx}"
                assert loc in obj["options"], f"Missing options.{loc} in {idx}"
                assert len(obj["options"][loc]) == 4, f"options.{loc} must have 4 items in {idx}"
            result.append(obj)
            idx += 1
    return result

def main():
    questions = build_questions()
    assert len(questions) == 100
    out = os.path.join(os.path.dirname(__file__), "questions.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)
        f.write("\n")
    with open(out, "r", encoding="utf-8") as f:
        line_count = sum(1 for _ in f)
    print(f"Wrote {len(questions)} questions to {out}")
    print(f"Line count: {line_count}")

if __name__ == "__main__":
    main()
