#!/usr/bin/env python3
"""Generate questions.json for Daily Football Quiz MVP."""
import json
import os

LOCALES = ["en", "hr", "de", "bs", "es", "pt", "sr", "fr", "it", "nl", "tr", "ar"]

def make_id(n):
    return f"aaaaaaaa-{n:04d}-4000-8000-000000000{n:03d}"

def q(text, opts, correct, category):
    """text and opts are dicts keyed by locale."""
    return {
        "id": None,
        "category": category,
        "correct_option_index": correct,
        "question_text": text,
        "options": opts,
    }

# Each entry: (question_text dict, options dict, correct_index)
# Options dict: locale -> [A, B, C, D]

QUESTIONS = []

# ========== WORLD CUP (001-020) ==========
WORLD_CUP = [
    (
        {
            "en": "Which country won the 2022 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2022.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 2022?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2022.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 2022?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 2022?",
            "sr": "Која је земља освојила Светско првенство у фудбалу 2022.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 2022 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 2022?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 2022?",
            "tr": "2022 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 2022؟",
        },
        {
            "en": ["Argentina", "France", "Brazil", "Croatia"],
            "hr": ["Argentina", "Francuska", "Brazil", "Hrvatska"],
            "de": ["Argentinien", "Frankreich", "Brasilien", "Kroatien"],
            "bs": ["Argentina", "Francuska", "Brazil", "Hrvatska"],
            "es": ["Argentina", "Francia", "Brasil", "Croacia"],
            "pt": ["Argentina", "França", "Brasil", "Croácia"],
            "sr": ["Аргентина", "Француска", "Бразил", "Хрватска"],
            "fr": ["Argentine", "France", "Brésil", "Croatie"],
            "it": ["Argentina", "Francia", "Brasile", "Croazia"],
            "nl": ["Argentinië", "Frankrijk", "Brazilië", "Kroatië"],
            "tr": ["Arjantin", "Fransa", "Brezilya", "Hırvatistan"],
            "ar": ["الأرجنتين", "فرنسا", "البرازيل", "كرواتيا"],
        },
        0,
    ),
    (
        {
            "en": "Which country has won the most FIFA World Cup titles?",
            "hr": "Koja zemlja ima najviše naslova svjetskog prvaka u nogometu?",
            "de": "Welches Land hat die meisten FIFA-Weltmeistertitel gewonnen?",
            "bs": "Koja zemlja ima najviše naslova svjetskog prvaka u nogometu?",
            "es": "¿Qué país ha ganado más títulos de la Copa Mundial de la FIFA?",
            "pt": "Qual país venceu mais títulos da Copa do Mundo da FIFA?",
            "sr": "Која земља има највише титула светског првака у фудбалу?",
            "fr": "Quel pays a remporté le plus de titres de Coupe du monde de la FIFA ?",
            "it": "Quale paese ha vinto più titoli di Coppa del Mondo FIFA?",
            "nl": "Welk land heeft de meeste FIFA Wereldkampioenschappen gewonnen?",
            "tr": "En fazla FIFA Dünya Kupası şampiyonluğuna sahip ülke hangisidir?",
            "ar": "أي دولة فازت بأكبر عدد من كؤوس العالم؟",
        },
        {
            "en": ["Brazil", "Germany", "Italy", "Argentina"],
            "hr": ["Brazil", "Njemačka", "Italija", "Argentina"],
            "de": ["Brasilien", "Deutschland", "Italien", "Argentinien"],
            "bs": ["Brazil", "Njemačka", "Italija", "Argentina"],
            "es": ["Brasil", "Alemania", "Italia", "Argentina"],
            "pt": ["Brasil", "Alemanha", "Itália", "Argentina"],
            "sr": ["Бразил", "Немачка", "Италија", "Аргентина"],
            "fr": ["Brésil", "Allemagne", "Italie", "Argentine"],
            "it": ["Brasile", "Germania", "Italia", "Argentina"],
            "nl": ["Brazilië", "Duitsland", "Italië", "Argentinië"],
            "tr": ["Brezilya", "Almanya", "İtalya", "Arjantin"],
            "ar": ["البرازيل", "ألمانيا", "إيطاليا", "الأرجنتين"],
        },
        0,
    ),
    (
        {
            "en": "In which year was the first FIFA World Cup held?",
            "hr": "U kojoj godini je održano prvo FIFA Svjetsko prvenstvo?",
            "de": "In welchem Jahr fand die erste FIFA-Weltmeisterschaft statt?",
            "bs": "U kojoj godini je održano prvo FIFA Svjetsko prvenstvo?",
            "es": "¿En qué año se celebró la primera Copa Mundial de la FIFA?",
            "pt": "Em que ano foi realizada a primeira Copa do Mundo da FIFA?",
            "sr": "У којој години је одржано прво Светско првенство у фудбалу?",
            "fr": "En quelle année a eu lieu la première Coupe du monde de la FIFA ?",
            "it": "In quale anno si è svolta la prima Coppa del Mondo FIFA?",
            "nl": "In welk jaar werd het eerste FIFA Wereldkampioenschap gehouden?",
            "tr": "İlk FIFA Dünya Kupası hangi yılda düzenlendi?",
            "ar": "في أي عام أقيمت أول كأس عالم لكرة القدم؟",
        },
        {
            "en": ["1930", "1928", "1934", "1926"],
            "hr": ["1930.", "1928.", "1934.", "1926."],
            "de": ["1930", "1928", "1934", "1926"],
            "bs": ["1930.", "1928.", "1934.", "1926."],
            "es": ["1930", "1928", "1934", "1926"],
            "pt": ["1930", "1928", "1934", "1926"],
            "sr": ["1930.", "1928.", "1934.", "1926."],
            "fr": ["1930", "1928", "1934", "1926"],
            "it": ["1930", "1928", "1934", "1926"],
            "nl": ["1930", "1928", "1934", "1926"],
            "tr": ["1930", "1928", "1934", "1926"],
            "ar": ["1930", "1928", "1934", "1926"],
        },
        0,
    ),
    (
        {
            "en": "Which country hosted the 2018 FIFA World Cup?",
            "hr": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 2018.?",
            "de": "Welches Land war Gastgeber der FIFA-Weltmeisterschaft 2018?",
            "bs": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 2018.?",
            "es": "¿Qué país fue sede de la Copa Mundial de la FIFA 2018?",
            "pt": "Qual país sediou a Copa do Mundo da FIFA de 2018?",
            "sr": "Која је земља била домаћин Светског првенства 2018.?",
            "fr": "Quel pays a accueilli la Coupe du monde de la FIFA 2018 ?",
            "it": "Quale paese ha ospitato la Coppa del Mondo FIFA 2018?",
            "nl": "Welk land organiseerde het FIFA Wereldkampioenschap 2018?",
            "tr": "2018 FIFA Dünya Kupası'na hangi ülke ev sahipliği yaptı?",
            "ar": "أي دولة استضافت كأس العالم 2018؟",
        },
        {
            "en": ["Russia", "Qatar", "Brazil", "South Africa"],
            "hr": ["Rusija", "Katar", "Brazil", "Južna Afrika"],
            "de": ["Russland", "Katar", "Brasilien", "Südafrika"],
            "bs": ["Rusija", "Katar", "Brazil", "Južna Afrika"],
            "es": ["Rusia", "Catar", "Brasil", "Sudáfrica"],
            "pt": ["Rússia", "Catar", "Brasil", "África do Sul"],
            "sr": ["Русија", "Катар", "Бразил", "Јужна Африка"],
            "fr": ["Russie", "Qatar", "Brésil", "Afrique du Sud"],
            "it": ["Russia", "Qatar", "Brasile", "Sudafrica"],
            "nl": ["Rusland", "Qatar", "Brazilië", "Zuid-Afrika"],
            "tr": ["Rusya", "Katar", "Brezilya", "Güney Afrika"],
            "ar": ["روسيا", "قطر", "البرازيل", "جنوب أفريقيا"],
        },
        0,
    ),
    (
        {
            "en": "Who is the all-time top scorer in FIFA World Cup history?",
            "hr": "Tko je najbolji strijelac u povijesti FIFA Svjetskog prvenstva?",
            "de": "Wer ist der Rekordtorschütze in der Geschichte der FIFA-Weltmeisterschaft?",
            "bs": "Ko je najbolji strijelac u historiji FIFA Svjetskog prvenstva?",
            "es": "¿Quién es el máximo goleador histórico de la Copa Mundial de la FIFA?",
            "pt": "Quem é o maior artilheiro da história da Copa do Mundo da FIFA?",
            "sr": "Ко је најбољи стрелац у историји Светског првенства?",
            "fr": "Qui est le meilleur buteur de l'histoire de la Coupe du monde de la FIFA ?",
            "it": "Chi è il miglior marcatore di sempre della Coppa del Mondo FIFA?",
            "nl": "Wie is de topscorer aller tijden op het FIFA Wereldkampioenschap?",
            "tr": "FIFA Dünya Kupası tarihinin en golcü oyuncusu kimdir?",
            "ar": "من هو الهداف التاريخي لكأس العالم؟",
        },
        {
            "en": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "hr": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "de": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "bs": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "es": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "pt": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "sr": ["Мирослав Клозе", "Роналдо Назарио", "Герд Милер", "Пеле"],
            "fr": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "it": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "nl": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "tr": ["Miroslav Klose", "Ronaldo Nazário", "Gerd Müller", "Pelé"],
            "ar": ["ميروسلاف كلوزه", "رونالدو نازاريو", "غيرد مولر", "بيليه"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 2014 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2014.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 2014?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2014.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 2014?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 2014?",
            "sr": "Која је земља освојила Светско првенство 2014.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 2014 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 2014?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 2014?",
            "tr": "2014 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 2014؟",
        },
        {
            "en": ["Germany", "Argentina", "Brazil", "Netherlands"],
            "hr": ["Njemačka", "Argentina", "Brazil", "Nizozemska"],
            "de": ["Deutschland", "Argentinien", "Brasilien", "Niederlande"],
            "bs": ["Njemačka", "Argentina", "Brazil", "Holandija"],
            "es": ["Alemania", "Argentina", "Brasil", "Países Bajos"],
            "pt": ["Alemanha", "Argentina", "Brasil", "Holanda"],
            "sr": ["Немачка", "Аргентина", "Бразил", "Холандија"],
            "fr": ["Allemagne", "Argentine", "Brésil", "Pays-Bas"],
            "it": ["Germania", "Argentina", "Brasile", "Paesi Bassi"],
            "nl": ["Duitsland", "Argentinië", "Brazilië", "Nederland"],
            "tr": ["Almanya", "Arjantin", "Brezilya", "Hollanda"],
            "ar": ["ألمانيا", "الأرجنتين", "البرازيل", "هولندا"],
        },
        0,
    ),
    (
        {
            "en": "Which country hosted the 2010 FIFA World Cup?",
            "hr": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 2010.?",
            "de": "Welches Land war Gastgeber der FIFA-Weltmeisterschaft 2010?",
            "bs": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 2010.?",
            "es": "¿Qué país fue sede de la Copa Mundial de la FIFA 2010?",
            "pt": "Qual país sediou a Copa do Mundo da FIFA de 2010?",
            "sr": "Која је земља била домаћин Светског првенства 2010.?",
            "fr": "Quel pays a accueilli la Coupe du monde de la FIFA 2010 ?",
            "it": "Quale paese ha ospitato la Coppa del Mondo FIFA 2010?",
            "nl": "Welk land organiseerde het FIFA Wereldkampioenschap 2010?",
            "tr": "2010 FIFA Dünya Kupası'na hangi ülke ev sahipliği yaptı?",
            "ar": "أي دولة استضافت كأس العالم 2010؟",
        },
        {
            "en": ["South Africa", "Germany", "Brazil", "Japan"],
            "hr": ["Južna Afrika", "Njemačka", "Brazil", "Japan"],
            "de": ["Südafrika", "Deutschland", "Brasilien", "Japan"],
            "bs": ["Južna Afrika", "Njemačka", "Brazil", "Japan"],
            "es": ["Sudáfrica", "Alemania", "Brasil", "Japón"],
            "pt": ["África do Sul", "Alemanha", "Brasil", "Japão"],
            "sr": ["Јужна Африка", "Немачка", "Бразил", "Јапан"],
            "fr": ["Afrique du Sud", "Allemagne", "Brésil", "Japon"],
            "it": ["Sudafrica", "Germania", "Brasile", "Giappone"],
            "nl": ["Zuid-Afrika", "Duitsland", "Brazilië", "Japan"],
            "tr": ["Güney Afrika", "Almanya", "Brezilya", "Japonya"],
            "ar": ["جنوب أفريقيا", "ألمانيا", "البرازيل", "اليابان"],
        },
        0,
    ),
    (
        {
            "en": "Who scored the 'Hand of God' goal at the 1986 World Cup?",
            "hr": "Tko je postigao gol 'Ruka Božja' na Svjetskom prvenstvu 1986.?",
            "de": "Wer erzielte das 'Hand Gottes'-Tor bei der WM 1986?",
            "bs": "Ko je postigao gol 'Ruka Božja' na Svjetskom prvenstvu 1986.?",
            "es": "¿Quién marcó el gol de la 'Mano de Dios' en el Mundial de 1986?",
            "pt": "Quem marcou o gol da 'Mão de Deus' na Copa de 1986?",
            "sr": "Ко је постигао гол 'Рука Божја' на Светском првенству 1986.?",
            "fr": "Qui a marqué le but de la 'Main de Dieu' en 1986 ?",
            "it": "Chi segnò il gol della 'Mano di Dio' ai Mondiali 1986?",
            "nl": "Wie scoorde het 'Hand Gods'-doelpunt op het WK 1986?",
            "tr": "1986 Dünya Kupası'nda 'Tanrı'nın Eli' golünü kim attı?",
            "ar": "من سجل هدف 'يد الله' في كأس العالم 1986؟",
        },
        {
            "en": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "hr": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "de": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "bs": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "es": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "pt": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "sr": ["Дијего Марадона", "Пеле", "Гари Лајнкер", "Мишел Платини"],
            "fr": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "it": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "nl": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "tr": ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
            "ar": ["دييغو مارادونا", "بيليه", "غاري لاينكر", "ميشيل بلاتيني"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 2006 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2006.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 2006?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 2006.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 2006?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 2006?",
            "sr": "Која је земља освојила Светско првенство 2006.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 2006 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 2006?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 2006?",
            "tr": "2006 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 2006؟",
        },
        {
            "en": ["Italy", "France", "Germany", "Brazil"],
            "hr": ["Italija", "Francuska", "Njemačka", "Brazil"],
            "de": ["Italien", "Frankreich", "Deutschland", "Brasilien"],
            "bs": ["Italija", "Francuska", "Njemačka", "Brazil"],
            "es": ["Italia", "Francia", "Alemania", "Brasil"],
            "pt": ["Itália", "França", "Alemanha", "Brasil"],
            "sr": ["Италија", "Француска", "Немачка", "Бразил"],
            "fr": ["Italie", "France", "Allemagne", "Brésil"],
            "it": ["Italia", "Francia", "Germania", "Brasile"],
            "nl": ["Italië", "Frankrijk", "Duitsland", "Brazilië"],
            "tr": ["İtalya", "Fransa", "Almanya", "Brezilya"],
            "ar": ["إيطاليا", "فرنسا", "ألمانيا", "البرازيل"],
        },
        0,
    ),
    (
        {
            "en": "Which country hosted the first FIFA World Cup in 1930?",
            "hr": "Koja je zemlja bila domaćin prvog FIFA Svjetskog prvenstva 1930.?",
            "de": "Welches Land war Gastgeber der ersten FIFA-Weltmeisterschaft 1930?",
            "bs": "Koja je zemlja bila domaćin prvog FIFA Svjetskog prvenstva 1930.?",
            "es": "¿Qué país fue sede de la primera Copa Mundial de la FIFA en 1930?",
            "pt": "Qual país sediou a primeira Copa do Mundo da FIFA em 1930?",
            "sr": "Која је земља била домаћин првог Светског првенства 1930.?",
            "fr": "Quel pays a accueilli la première Coupe du monde de la FIFA en 1930 ?",
            "it": "Quale paese ha ospitato la prima Coppa del Mondo FIFA nel 1930?",
            "nl": "Welk land organiseerde het eerste FIFA Wereldkampioenschap in 1930?",
            "tr": "1930'da ilk FIFA Dünya Kupası'na hangi ülke ev sahipliği yaptı?",
            "ar": "أي دولة استضافت أول كأس عالم في عام 1930؟",
        },
        {
            "en": ["Uruguay", "Brazil", "Italy", "Argentina"],
            "hr": ["Urugvaj", "Brazil", "Italija", "Argentina"],
            "de": ["Uruguay", "Brasilien", "Italien", "Argentinien"],
            "bs": ["Urugvaj", "Brazil", "Italija", "Argentina"],
            "es": ["Uruguay", "Brasil", "Italia", "Argentina"],
            "pt": ["Uruguai", "Brasil", "Itália", "Argentina"],
            "sr": ["Уругвај", "Бразил", "Италија", "Аргентина"],
            "fr": ["Uruguay", "Brésil", "Italie", "Argentine"],
            "it": ["Uruguay", "Brasile", "Italia", "Argentina"],
            "nl": ["Uruguay", "Brazilië", "Italië", "Argentinië"],
            "tr": ["Uruguay", "Brezilya", "İtalya", "Arjantin"],
            "ar": ["الأوروغواي", "البرازيل", "إيطاليا", "الأرجنتين"],
        },
        0,
    ),
    (
        {
            "en": "How many teams participated in the 2022 FIFA World Cup?",
            "hr": "Koliko je reprezentacija sudjelovalo na FIFA Svjetskom prvenstvu 2022.?",
            "de": "Wie viele Teams nahmen an der FIFA-Weltmeisterschaft 2022 teil?",
            "bs": "Koliko je reprezentacija učestvovalo na FIFA Svjetskom prvenstvu 2022.?",
            "es": "¿Cuántos equipos participaron en la Copa Mundial de la FIFA 2022?",
            "pt": "Quantas seleções participaram da Copa do Mundo da FIFA de 2022?",
            "sr": "Колико је репрезентација учествовало на Светском првенству 2022.?",
            "fr": "Combien d'équipes ont participé à la Coupe du monde de la FIFA 2022 ?",
            "it": "Quante squadre hanno partecipato alla Coppa del Mondo FIFA 2022?",
            "nl": "Hoeveel teams namen deel aan het FIFA Wereldkampioenschap 2022?",
            "tr": "2022 FIFA Dünya Kupası'na kaç takım katıldı?",
            "ar": "كم عدد المنتخبات التي شاركت في كأس العالم 2022؟",
        },
        {
            "en": ["32", "24", "48", "16"],
            "hr": ["32", "24", "48", "16"],
            "de": ["32", "24", "48", "16"],
            "bs": ["32", "24", "48", "16"],
            "es": ["32", "24", "48", "16"],
            "pt": ["32", "24", "48", "16"],
            "sr": ["32", "24", "48", "16"],
            "fr": ["32", "24", "48", "16"],
            "it": ["32", "24", "48", "16"],
            "nl": ["32", "24", "48", "16"],
            "tr": ["32", "24", "48", "16"],
            "ar": ["32", "24", "48", "16"],
        },
        0,
    ),
    (
        {
            "en": "Which player won the Golden Boot at the 2018 World Cup?",
            "hr": "Koji je igrač osvojio Zlatnu kopačku na Svjetskom prvenstvu 2018.?",
            "de": "Welcher Spieler gewann den Goldenen Schuh bei der WM 2018?",
            "bs": "Koji je igrač osvojio Zlatnu kopačku na Svjetskom prvenstvu 2018.?",
            "es": "¿Qué jugador ganó la Bota de Oro en el Mundial de 2018?",
            "pt": "Qual jogador venceu a Bola de Ouro na Copa de 2018?",
            "sr": "Који је играч освојио Златну ципелу на Светском првенству 2018.?",
            "fr": "Quel joueur a remporté le Soulier d'or en 2018 ?",
            "it": "Quale giocatore ha vinto la Scarpa d'oro ai Mondiali 2018?",
            "nl": "Welke speler won de Gouden Schoen op het WK 2018?",
            "tr": "2018 Dünya Kupası'nda Altın Ayakkabı'yı hangi oyuncu kazandı?",
            "ar": "من فاز بالحذاء الذهبي في كأس العالم 2018؟",
        },
        {
            "en": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "hr": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "de": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "bs": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "es": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "pt": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "sr": ["Хари Кејн", "Антуан Гризман", "Ромелу Лукаку", "Кристијано Роналдо"],
            "fr": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "it": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "nl": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "tr": ["Harry Kane", "Antoine Griezmann", "Romelu Lukaku", "Cristiano Ronaldo"],
            "ar": ["هاري كين", "أنطوان غريزمان", "روميلو لوكاكو", "كريستيانو رونالدو"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 1998 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1998.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 1998?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1998.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 1998?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 1998?",
            "sr": "Која је земља освојила Светско првенство 1998.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 1998 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 1998?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 1998?",
            "tr": "1998 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 1998؟",
        },
        {
            "en": ["France", "Brazil", "Croatia", "Netherlands"],
            "hr": ["Francuska", "Brazil", "Hrvatska", "Nizozemska"],
            "de": ["Frankreich", "Brasilien", "Kroatien", "Niederlande"],
            "bs": ["Francuska", "Brazil", "Hrvatska", "Holandija"],
            "es": ["Francia", "Brasil", "Croacia", "Países Bajos"],
            "pt": ["França", "Brasil", "Croácia", "Holanda"],
            "sr": ["Француска", "Бразил", "Хрватска", "Холандија"],
            "fr": ["France", "Brésil", "Croatie", "Pays-Bas"],
            "it": ["Francia", "Brasile", "Croazia", "Paesi Bassi"],
            "nl": ["Frankrijk", "Brazilië", "Kroatië", "Nederland"],
            "tr": ["Fransa", "Brezilya", "Hırvatistan", "Hollanda"],
            "ar": ["فرنسا", "البرازيل", "كرواتيا", "هولندا"],
        },
        0,
    ),
    (
        {
            "en": "Which country hosted the 2002 FIFA World Cup (co-hosted)?",
            "hr": "Koje su zemlje bile domaćini FIFA Svjetskog prvenstva 2002.?",
            "de": "Welche Länder waren Gastgeber der FIFA-Weltmeisterschaft 2002?",
            "bs": "Koje su zemlje bile domaćini FIFA Svjetskog prvenstva 2002.?",
            "es": "¿Qué países fueron sede de la Copa Mundial de la FIFA 2002?",
            "pt": "Quais países sediaram a Copa do Mundo da FIFA de 2002?",
            "sr": "Које су земље биле домаћини Светског првенства 2002.?",
            "fr": "Quels pays ont co-organisé la Coupe du monde de la FIFA 2002 ?",
            "it": "Quali paesi hanno ospitato la Coppa del Mondo FIFA 2002?",
            "nl": "Welke landen organiseerden het FIFA Wereldkampioenschap 2002?",
            "tr": "2002 FIFA Dünya Kupası'na hangi ülkeler ev sahipliği yaptı?",
            "ar": "أي دولتين استضافتا كأس العالم 2002؟",
        },
        {
            "en": ["Japan and South Korea", "China and Japan", "Australia and New Zealand", "Qatar and UAE"],
            "hr": ["Japan i Južna Koreja", "Kina i Japan", "Australija i Novi Zeland", "Katar i UAE"],
            "de": ["Japan und Südkorea", "China und Japan", "Australien und Neuseeland", "Katar und VAE"],
            "bs": ["Japan i Južna Koreja", "Kina i Japan", "Australija i Novi Zeland", "Katar i UAE"],
            "es": ["Japón y Corea del Sur", "China y Japón", "Australia y Nueva Zelanda", "Catar y EAU"],
            "pt": ["Japão e Coreia do Sul", "China e Japão", "Austrália e Nova Zelândia", "Catar e Emirados"],
            "sr": ["Јапан и Јужна Кореја", "Кина и Јапан", "Аустралија и Нови Зеланд", "Катар и УАЕ"],
            "fr": ["Japon et Corée du Sud", "Chine et Japon", "Australie et Nouvelle-Zélande", "Qatar et EAU"],
            "it": ["Giappone e Corea del Sud", "Cina e Giappone", "Australia e Nuova Zelanda", "Qatar e Emirati"],
            "nl": ["Japan en Zuid-Korea", "China en Japan", "Australië en Nieuw-Zeeland", "Qatar en VAE"],
            "tr": ["Japonya ve Güney Kore", "Çin ve Japonya", "Avustralya ve Yeni Zelanda", "Katar ve BAE"],
            "ar": ["اليابان وكوريا الجنوبية", "الصين واليابان", "أستراليا ونيوزيلندا", "قطر والإمارات"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 1958 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1958.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 1958?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1958.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 1958?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 1958?",
            "sr": "Која је земља освојила Светско првенство 1958.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 1958 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 1958?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 1958?",
            "tr": "1958 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 1958؟",
        },
        {
            "en": ["Brazil", "Sweden", "France", "West Germany"],
            "hr": ["Brazil", "Švedska", "Francuska", "Zapadna Njemačka"],
            "de": ["Brasilien", "Schweden", "Frankreich", "Westdeutschland"],
            "bs": ["Brazil", "Švedska", "Francuska", "Zapadna Njemačka"],
            "es": ["Brasil", "Suecia", "Francia", "Alemania Occidental"],
            "pt": ["Brasil", "Suécia", "França", "Alemanha Ocidental"],
            "sr": ["Бразил", "Шведска", "Француска", "Западна Немачка"],
            "fr": ["Brésil", "Suède", "France", "Allemagne de l'Ouest"],
            "it": ["Brasile", "Svezia", "Francia", "Germania Ovest"],
            "nl": ["Brazilië", "Zweden", "Frankrijk", "West-Duitsland"],
            "tr": ["Brezilya", "İsveç", "Fransa", "Batı Almanya"],
            "ar": ["البرازيل", "السويد", "فرنسا", "ألمانيا الغربية"],
        },
        0,
    ),
    (
        {
            "en": "Who scored a hat-trick in the 1966 World Cup final for England?",
            "hr": "Tko je postigao tri gola u finalu Svjetskog prvenstva 1966. za Englesku?",
            "de": "Wer erzielte einen Hattrick im WM-Finale 1966 für England?",
            "bs": "Ko je postigao tri gola u finalu Svjetskog prvenstva 1966. za Englesku?",
            "es": "¿Quién marcó un hat-trick en la final del Mundial de 1966 para Inglaterra?",
            "pt": "Quem marcou um hat-trick na final da Copa de 1966 pela Inglaterra?",
            "sr": "Ко је постигао три гола у финалу Светског првенства 1966. за Енглеску?",
            "fr": "Qui a marqué un triplé en finale de la Coupe du monde 1966 pour l'Angleterre ?",
            "it": "Chi segnò una tripletta nella finale dei Mondiali 1966 per l'Inghilterra?",
            "nl": "Wie scoorde een hattrick in de WK-finale 1966 voor Engeland?",
            "tr": "1966 Dünya Kupası finalinde İngiltere adına hat-trick yapan oyuncu kimdir?",
            "ar": "من سجل ثلاثية في نهائي كأس العالم 1966 مع إنجلترا؟",
        },
        {
            "en": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "hr": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "de": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "bs": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "es": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "pt": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "sr": ["Џеф Херст", "Боби Чарлтон", "Боби Мур", "Џими Гривз"],
            "fr": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "it": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "nl": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "tr": ["Geoff Hurst", "Bobby Charlton", "Bobby Moore", "Jimmy Greaves"],
            "ar": ["جيف هيرست", "بوبي تشارلتون", "بوبي مور", "جيمي غريفز"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 2022 World Cup final on penalties?",
            "hr": "Koja je zemlja osvojila finale Svjetskog prvenstva 2022. na jedanaestercima?",
            "de": "Welches Land gewann das WM-Finale 2022 im Elfmeterschießen?",
            "bs": "Koja je zemlja osvojila finale Svjetskog prvenstva 2022. na jedanaestercima?",
            "es": "¿Qué país ganó la final del Mundial 2022 en los penaltis?",
            "pt": "Qual país venceu a final da Copa de 2022 nos pênaltis?",
            "sr": "Која је земља освојила финале Светског првенства 2022. на пеналима?",
            "fr": "Quel pays a remporté la finale de la Coupe du monde 2022 aux tirs au but ?",
            "it": "Quale paese ha vinto la finale dei Mondiali 2022 ai rigori?",
            "nl": "Welk land won de WK-finale 2022 na strafschoppen?",
            "tr": "2022 Dünya Kupası finalini penaltılarla hangi ülke kazandı?",
            "ar": "أي دولة فازت بنهائي كأس العالم 2022 بركلات الترجيح؟",
        },
        {
            "en": ["Argentina", "France", "Croatia", "Morocco"],
            "hr": ["Argentina", "Francuska", "Hrvatska", "Maroko"],
            "de": ["Argentinien", "Frankreich", "Kroatien", "Marokko"],
            "bs": ["Argentina", "Francuska", "Hrvatska", "Maroko"],
            "es": ["Argentina", "Francia", "Croacia", "Marruecos"],
            "pt": ["Argentina", "França", "Croácia", "Marrocos"],
            "sr": ["Аргентина", "Француска", "Хрватска", "Мароко"],
            "fr": ["Argentine", "France", "Croatie", "Maroc"],
            "it": ["Argentina", "Francia", "Croazia", "Marocco"],
            "nl": ["Argentinië", "Frankrijk", "Kroatië", "Marokko"],
            "tr": ["Arjantin", "Fransa", "Hırvatistan", "Fas"],
            "ar": ["الأرجنتين", "فرنسا", "كرواتيا", "المغرب"],
        },
        0,
    ),
    (
        {
            "en": "Which country hosted the 1994 FIFA World Cup?",
            "hr": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 1994.?",
            "de": "Welches Land war Gastgeber der FIFA-Weltmeisterschaft 1994?",
            "bs": "Koja je zemlja bila domaćin FIFA Svjetskog prvenstva 1994.?",
            "es": "¿Qué país fue sede de la Copa Mundial de la FIFA 1994?",
            "pt": "Qual país sediou a Copa do Mundo da FIFA de 1994?",
            "sr": "Која је земља била домаћин Светског првенства 1994.?",
            "fr": "Quel pays a accueilli la Coupe du monde de la FIFA 1994 ?",
            "it": "Quale paese ha ospitato la Coppa del Mondo FIFA 1994?",
            "nl": "Welk land organiseerde het FIFA Wereldkampioenschap 1994?",
            "tr": "1994 FIFA Dünya Kupası'na hangi ülke ev sahipliği yaptı?",
            "ar": "أي دولة استضافت كأس العالم 1994؟",
        },
        {
            "en": ["United States", "Mexico", "Brazil", "Canada"],
            "hr": ["Sjedinjene Američke Države", "Meksiko", "Brazil", "Kanada"],
            "de": ["Vereinigte Staaten", "Mexiko", "Brasilien", "Kanada"],
            "bs": ["Sjedinjene Američke Države", "Meksiko", "Brazil", "Kanada"],
            "es": ["Estados Unidos", "México", "Brasil", "Canadá"],
            "pt": ["Estados Unidos", "México", "Brasil", "Canadá"],
            "sr": ["Сједињене Америчке Државе", "Мексико", "Бразил", "Канада"],
            "fr": ["États-Unis", "Mexique", "Brésil", "Canada"],
            "it": ["Stati Uniti", "Messico", "Brasile", "Canada"],
            "nl": ["Verenigde Staten", "Mexico", "Brazilië", "Canada"],
            "tr": ["Amerika Birleşik Devletleri", "Meksika", "Brezilya", "Kanada"],
            "ar": ["الولايات المتحدة", "المكسيك", "البرازيل", "كندا"],
        },
        0,
    ),
    (
        {
            "en": "Which country won the 1970 FIFA World Cup?",
            "hr": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1970.?",
            "de": "Welches Land gewann die FIFA-Weltmeisterschaft 1970?",
            "bs": "Koja je zemlja osvojila FIFA Svjetsko prvenstvo 1970.?",
            "es": "¿Qué país ganó la Copa Mundial de la FIFA 1970?",
            "pt": "Qual país venceu a Copa do Mundo da FIFA de 1970?",
            "sr": "Која је земља освојила Светско првенство 1970.?",
            "fr": "Quel pays a remporté la Coupe du monde de la FIFA 1970 ?",
            "it": "Quale paese ha vinto la Coppa del Mondo FIFA 1970?",
            "nl": "Welk land won het FIFA Wereldkampioenschap 1970?",
            "tr": "1970 FIFA Dünya Kupası'nı hangi ülke kazandı?",
            "ar": "أي دولة فازت بكأس العالم 1970؟",
        },
        {
            "en": ["Brazil", "Italy", "West Germany", "Uruguay"],
            "hr": ["Brazil", "Italija", "Zapadna Njemačka", "Urugvaj"],
            "de": ["Brasilien", "Italien", "Westdeutschland", "Uruguay"],
            "bs": ["Brazil", "Italija", "Zapadna Njemačka", "Urugvaj"],
            "es": ["Brasil", "Italia", "Alemania Occidental", "Uruguay"],
            "pt": ["Brasil", "Itália", "Alemanha Ocidental", "Uruguai"],
            "sr": ["Бразил", "Италија", "Западна Немачка", "Уругвај"],
            "fr": ["Brésil", "Italie", "Allemagne de l'Ouest", "Uruguay"],
            "it": ["Brasile", "Italia", "Germania Ovest", "Uruguay"],
            "nl": ["Brazilië", "Italië", "West-Duitsland", "Uruguay"],
            "tr": ["Brezilya", "İtalya", "Batı Almanya", "Uruguay"],
            "ar": ["البرازيل", "إيطاليا", "ألمانيا الغربية", "الأوروغواي"],
        },
        0,
    ),
    (
        {
            "en": "Which country will host the 2026 FIFA World Cup (co-hosted)?",
            "hr": "Koje će zemlje biti domaćini FIFA Svjetskog prvenstva 2026.?",
            "de": "Welche Länder werden Gastgeber der FIFA-Weltmeisterschaft 2026 sein?",
            "bs": "Koje će zemlje biti domaćini FIFA Svjetskog prvenstva 2026.?",
            "es": "¿Qué países serán sede de la Copa Mundial de la FIFA 2026?",
            "pt": "Quais países sediarão a Copa do Mundo da FIFA de 2026?",
            "sr": "Које ће земље бити домаћини Светског првенства 2026.?",
            "fr": "Quels pays accueilleront la Coupe du monde de la FIFA 2026 ?",
            "it": "Quali paesi ospiteranno la Coppa del Mondo FIFA 2026?",
            "nl": "Welke landen organiseren het FIFA Wereldkampioenschap 2026?",
            "tr": "2026 FIFA Dünya Kupası'na hangi ülkeler ev sahipliği yapacak?",
            "ar": "أي دول ستستضيف كأس العالم 2026؟",
        },
        {
            "en": ["USA, Mexico and Canada", "Qatar and Saudi Arabia", "Brazil and Argentina", "Spain and Portugal"],
            "hr": ["SAD, Meksiko i Kanada", "Katar i Saudijska Arabija", "Brazil i Argentina", "Španjolska i Portugal"],
            "de": ["USA, Mexiko und Kanada", "Katar und Saudi-Arabien", "Brasilien und Argentinien", "Spanien und Portugal"],
            "bs": ["SAD, Meksiko i Kanada", "Katar i Saudijska Arabija", "Brazil i Argentina", "Španija i Portugal"],
            "es": ["EE.UU., México y Canadá", "Catar y Arabia Saudita", "Brasil y Argentina", "España y Portugal"],
            "pt": ["EUA, México e Canadá", "Catar e Arábia Saudita", "Brasil e Argentina", "Espanha e Portugal"],
            "sr": ["САД, Мексико и Канада", "Катар и Саудијска Арабија", "Бразил и Аргентина", "Шпанија и Португалија"],
            "fr": ["États-Unis, Mexique et Canada", "Qatar et Arabie saoudite", "Brésil et Argentine", "Espagne et Portugal"],
            "it": ["USA, Messico e Canada", "Qatar e Arabia Saudita", "Brasile e Argentina", "Spagna e Portogallo"],
            "nl": ["VS, Mexico en Canada", "Qatar en Saoedi-Arabië", "Brazilië en Argentinië", "Spanje en Portugal"],
            "tr": ["ABD, Meksika ve Kanada", "Katar ve Suudi Arabistan", "Brezilya ve Arjantin", "İspanya ve Portekiz"],
            "ar": ["الولايات المتحدة والمكسيك وكندا", "قطر والسعودية", "البرازيل والأرجنتين", "إسبانيا والبرتغال"],
        },
        0,
    ),
]

assert len(WORLD_CUP) == 20
